# Variables
FRONTEND_DIR=apps/frontend
BACKEND_DIR=apps/backend

# Backend targets
dev:
	pnpm run dev

lint:
	pnpm run lint

format:
	pnpm run format

test:
	pnpm run test

health-check:
	pnpm run health-check

migrate:
	pnpm run migrate

migrate-undo:
	pnpm run migrate:undo

migrate-status:
	pnpm run migrate:status

seed:
	pnpm run seed:all

seed-undo:
	pnpm run seed:undo:all
