version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: backend-template-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend-template
    container_name: backend-template-api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - ./apps/backend-template/.env
    command: /bin/sh -c "pnpm run seed && pnpm run start"


volumes:
  postgres-data:
