name: 🛠️ Build, Lint, Test, Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Tests with Vitest
        run: pnpm test

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
